version: "3.8"

services:
  fund-agent-service: 
    #image: api-agent-service:latest
    build: .
    container_name: fund-api-agent-service-demo
    ports:
      - "8200:8200"
    #deploy:
    #  replicas: 3
    env_file:
      - .env
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3
    #  start_period: 40s
    restart: unless-stopped
